import type { Metadata } from 'next';
import './globals.css';
import TawkToChat from '@/components/TawkToChat';
import SalesNotification from '@/components/SalesNotification';

export const metadata: Metadata = {
  metadataBase: new URL('https://whiskeyeurope.org'),
  title: {
    default: 'Whiskey Europe | Rare Single Malts, Aged Whiskies & Collector Cellars',
    template: '%s | Whiskey Europe',
  },
  description:
    'Curated European boutique for rare single malts, Japanese Mizunara, Balvenie Tun series, Karuizawa ghost distilleries, Macallan Sherry Oak, Port Ellen vintage casks, antique Bourbons, and fine Cognacs. Bonded climate-controlled storage in Rotterdam with 100% authenticity guarantee and insured EU delivery.',
  keywords: [
    // General Brand & Category Queries
    'whiskey europe',
    'buy rare whisky europe',
    'single malt scotch europe',
    'japanese whisky europe',
    'bonded spirits cellar rotterdam',
    'bourbon allocations europe',
    'rare bottle allocations',
    'distillery origin map europe',

    // User Specified Target Whiskies & Bourbons
    'Jameson Whiskey',
    'Jameson Irish Whiskey',
    'Jameson Orange',
    'Jameson Black Barrel',
    'Jack Daniel\'s Whiskey',
    'Tennessee Whiskey',
    'Tennessee Honey',
    'Gentleman Jack',
    'Old No. 7',
    'Johnnie Walker Blue Label',
    'Johnnie Walker Black Label',
    'Johnnie Walker Red Label',
    'Skrewball Peanut Butter Whiskey',
    'Fireball Cinnamon Whiskey',
    'Basil Hayden\'s Bourbon Whiskey',
    'Buffalo Trace Kentucky Straight Bourbon',
    'Buffalo Trace Bourbon Cream',
    'Hibiki Japanese Harmony Whiskey',
    'Pendleton Whiskey',
    'Angel\'s Envy Bourbon Whiskey',
    'Blanton\'s Single Barrel Bourbon Whiskey',
    'Macallan Single Malt Scotch Whisky',
    'Uncle Nearest Premium Whiskey',
    'Jim Beam Bourbon Whiskey',
    'Booker\'s Bourbon Whiskey',
    'Monkey Shoulder Scotch Whisky',
    'Traveller Whiskey',
    'Traveller Whiskey Chris Stapleton',
    'Crown Royal Canadian Whisky',
    'Mactasker Whiskey',
    'Redbreast Single Pot Still Irish Whiskey',
    'Woodford Reserve Straight Bourbon',
    'Woodford Reserve Double Oaked Bourbon',
    'Bird Dog Flavored Whiskey',
    'Bulleit Straight Bourbon',
    'Bulleit Rye Whiskey',
    'Evan Williams Kentucky Straight Bourbon Whiskey',
    'Green Spot Single Pot Still Irish Whiskey',
    'High West Bourbon',
    'High West Whiskey',
    'WhistlePig Rye Whiskey',
    'Yamazaki Japanese Single Malt Whiskey',
    'Yamazaki 18',
    'Yamazaki 25',
    'Yamazaki 50',
    'Black Velvet Canadian Whisky',
    'George T. Stagg Straight Bourbon Whiskey',
    'Maker\'s Mark Straight Bourbon',
    'Maker\'s 46 Bourbon Whisky',
    'Nikka Japanese Whisky',
    'Nikka From The Barrel',
    'Nikka Taketsuru',
    'Suntory Toki Japanese Whisky',
    'TX Blended Whiskey',
    'TX Straight Bourbon',
    'Weller Straight Bourbon',
    'Weller Special Reserve',
    'Weller 12 Year',
    'Daniel Weller Spelt Wheat',
    'Wild Turkey Bourbon',
    'Wild Turkey 101 Bourbon',
    'Blackened American Whiskey',
    'Buchanan\'s Blended Scotch Whisky',
    'Cutty Sark Blended Scotch Whisky',
    'Indri Single Malt Indian Whisky',
    'Proper No. Twelve Irish Whiskey',
    'Sazerac Straight Rye Whiskey',
    'SirDavis American Whisky',
    'Still Austin Straight Bourbon',
    'Still Austin Whiskey',
    'Stranahan\'s Colorado Whiskey',
    'Tin Cup American Whiskey',
    'Bushmills Irish Whiskey',
    'Chattanooga Straight Bourbon Whiskey',
    'The Dalmore Single Malt Scotch Whisky',
    'Eagle Rare 10 Year',
    'Eagle Rare 12 Year Kentucky Straight Bourbon Whiskey',
    'Eagle Rare 25 Year Old',
    '1792 Small Batch Bourbon',
    '1792 Reserve Bourbon',
    'Barton 1792',
    'Knob Creek 9',
    'Knob Creek 12',
    'Knob Creek 21 Kentucky Straight Bourbon Whiskey',
    'Pappy Van Winkle Bourbon',
    'Old Rip Van Winkle Bourbon',
    'Penelope Straight Bourbon',
    'Stagg Straight Bourbon Whiskey',
    'Stagg Jr. Straight Bourbon Whiskey',
    'Willett Straight Bourbon',
    'Four Roses Kentucky Straight Bourbon',
    'Bardstown Bourbon',
    'Horse Soldier Straight Bourbon',
    'Michter\'s Straight Bourbon',
    'Michter\'s 10 Year Bourbon',
    'Michter\'s 25 Year Bourbon',
    'Elijah Craig Small Batch Bourbon',
    'Elijah Craig Barrel Strength',
    'Elijah Craig 18 Year Bourbon',
    'Brother\'s Bond Straight Bourbon',
    'Doc Holliday Straight Bourbon',
    'King of Kentucky Straight Bourbon',
    'Larceny Very Special Small Batch Bourbon',
    'Old Forester Bourbon',
    'Old Forester Birthday Bourbon',
    'Green River Straight Bourbon',
    'Green River Wheated Bourbon',
    'Heaven Hill Straight Bourbon',
    'Benchmark Kentucky Straight Bourbon',
    'Blade and Bow Kentucky Straight Bourbon',
    'Chicken Cock Kentucky Straight Bourbon',
    'Elmer T. Lee Single Barrel Bourbon',
    'Frank August Small Batch Bourbon',
    'New Riff Kentucky Straight Bourbon',
    'Old Grand-Dad Bourbon',
    'Rabbit Hole Straight Bourbon',
    'Blood Oath Bourbon Pact',
    'Calumet Farm Single Rack Black Bourbon',
    'Castle & Key Small Batch Bourbon',
    'Colonel E.H. Taylor Small Batch Bourbon',
    'Colonel E.H. Taylor Cured Oak',
    'Colonel E.H. Taylor Tornado Surviving',
    'Dettling 1867 Straight Bourbon',
    'Frey Ranch Straight Bourbon',
    'Madagascar Bourbon Vanilla Beans',
    'Madagascar Bourbon Vanilla Paste',
    'Old Crow Straight Bourbon',
    'Pinhook Straight Bourbon',
    'Redwood Empire Straight Bourbon',
    'Russell\'s Reserve Straight Bourbon',
    'Smoke Wagon Straight Bourbon',
    'Widow Jane 10 Year Straight Bourbon',
    'Woodinville Straight Bourbon',
    'Wolcott Kentucky Straight Bourbon',
    'Ancient Age Straight Bourbon',
    'Blue Run Straight Bourbon',
    'Peerless Small Batch Bourbon',
    'Rock Hill Farms Single Barrel Bourbon',
    'Yellowstone Select Kentucky Straight Bourbon',
    'A. Smith Bowman Cask Strength Bourbon',
    'Bib & Tucker Small Batch Bourbon',
    'Goose Island Bourbon County Brand Stout',
    'Garrison Brothers Texas Straight Bourbon',
    'Old Fitzgerald Bottled in Bond Bourbon',
    'Redemption Straight Bourbon',
    'Suntory The Chita Single Grain Whisky',
    'Hakushu Japanese Single Malt Whisky',
    'Hakushu 12',
    'Hakushu 18',
    'Hakushu 25',
    'Kaigan Japanese Whisky',
    'D\'Annam Japanese Whiskey Eau de Parfum',
    'D\'Annam Japanese Whiskey Spray',
    'Kaiyo Mizunara Oak Japanese Whisky',
    'Nobushi Japanese Blended Whisky',
    'Akashi Blended Japanese Whisky',
    'Akashi White Oak',
    'Kikori Japanese Rice Whiskey',
    'Maen Japanese Whisky',
    'Fuji Single Malt Japanese Whisky',
    'Ryujin Japanese Whisky',
    'Iwai Japanese Whisky',
    'Mars Shinshu',
    'Fuyu Small Batch Japanese Whisky',
    'Kurayoshi Pure Malt Japanese Whisky',
    'Hatozaki Japanese Blended Whisky',
    'Kanekou Okinawa Whisky',
    'Kyoto Japanese Whisky',
    'Meikakuna Japanese Whisky',
    'Sadashi Japanese Whisky',
    'Yamato Armor Takeda Edition Japanese Whisky',
    'Glencairn Whiskey Glass',
    'Glencairn Crystal Tumbler Sets',
    'Whiskey Advent Calendars 2025',
    'Whiskey Advent Calendars 2026',
    'Whiskey Smoker Kits',
    'Whiskey Stones',
    'Whiskey Barrel Planters',
    'Whiskey Aging Barrels',

    // Core Vintage Single Malts & Casks
    'Balvenie 17 Year Old Sherry Oak 70cl Whisky',
    'Balvenie 25 Year Old Single Barrel Traditional Oak 70cl Whisky',
    'Balvenie 30 Year Old 70cl Whisky',
    'Balvenie 50 Year Old Marriage 0614 70cl Whisky',
    'Balvenie Tun 1401 Batch 2 Whisky 70cl',
    'Karuizawa 1980 Golden Samurai 70cl Whisky',
    'Karuizawa 48 Year Old 1964 cask 3603 70cl Whisky',
    'Macallan 25 Year Old Sherry Oak 2023 Release 70cl Whisky',
    'Macallan 50 Year Old The Red Collection 2020 Release 70cl Whisky',
    'Port Ellen 40 Year Old Untold Stories Series 70cl Whisky',
    'Pappy Van Winkle 20 Year',
    'Pappy Van Winkle Family Reserve 23 Year',
  ],
  authors: [{ name: 'Whiskey Europe Sommelier & Cellar Master Team', url: 'https://whiskeyeurope.org' }],
  creator: 'Whiskey Europe',
  publisher: 'Whiskey Europe',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: 'https://whiskeyeurope.org',
    languages: {
      'en-GB': 'https://whiskeyeurope.org',
      'en-US': 'https://whiskeyeurope.org',
      'de-DE': 'https://whiskeyeurope.org',
      'fr-FR': 'https://whiskeyeurope.org',
      'nl-NL': 'https://whiskeyeurope.org',
      'x-default': 'https://whiskeyeurope.org',
    },
  },
  openGraph: {
    title: 'Whiskey Europe | Rare Single Malts, Aged Whiskies & Collector Cellars',
    description:
      'Explore European bonded cellar allocations: Balvenie DCS Compendium, Macallan Sherry Oak, Karuizawa, Yamazaki 18/25/50, Hibiki, Port Ellen, Blanton\'s, Weller, and Pappy Van Winkle.',
    url: 'https://whiskeyeurope.org',
    siteName: 'Whiskey Europe',
    images: [
      {
        url: 'https://lh3.googleusercontent.com/d/12Xn18KSHqyNIDRTEwZmH3-eIaT5LESZ6',
        width: 1200,
        height: 630,
        alt: 'Whiskey Europe Rare Vintage Cellar Collection',
      },
    ],
    locale: 'en_GB',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Whiskey Europe | Rare Single Malts & Collector Cellars',
    description:
      'Curated European boutique for rare single malts, Japanese Mizunara, Balvenie Tun, Port Ellen, and Bourbon allocations with insured EU delivery.',
    images: ['https://lh3.googleusercontent.com/d/12Xn18KSHqyNIDRTEwZmH3-eIaT5LESZ6'],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'PhoanpLbqcsYTQ2kraJh2NLn0rx1iqHqBpWiqrPt0Mk',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const websiteSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Whiskey Europe',
    url: 'https://whiskeyeurope.org',
    description:
      'European bonded online cellar for rare single malts, Japanese whiskies, vintage Scotches, Bourbons, and fine Cognacs.',
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: 'https://whiskeyeurope.org/shop?q={search_term_string}',
      },
      'query-input': 'required name=search_term_string',
    },
  };

  const organizationSchema = {
    '@context': 'https://schema.org',
    '@type': 'LiquorStore',
    name: 'Whiskey Europe',
    legalName: 'Whiskey Europe B.V.',
    url: 'https://whiskeyeurope.org',
    logo: 'https://whiskeyeurope.org/icon.png',
    image: 'https://lh3.googleusercontent.com/d/12Xn18KSHqyNIDRTEwZmH3-eIaT5LESZ6',
    email: 'contact@whiskeyeurope.org',
    telephone: '+31-10-890-4422',
    address: {
      '@type': 'PostalAddress',
      streetAddress: 'Willemskade 22, Port of Rotterdam Bonded Zone',
      addressLocality: 'Rotterdam',
      postalCode: '3016 DK',
      addressCountry: 'NL',
    },
    geo: {
      '@type': 'GeoCoordinates',
      latitude: 51.9126,
      longitude: 4.4812,
    },
    openingHoursSpecification: [
      {
        '@type': 'OpeningHoursSpecification',
        dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        opens: '08:00',
        closes: '18:00',
      },
    ],
    priceRange: '€€€€',
    paymentAccepted: 'Credit Card, SEPA Bank Transfer, Apple Pay, Klarna',
    currenciesAccepted: 'EUR, GBP, USD, CHF, JPY',
    knowsAbout: [
      'Jameson Irish Whiskey',
      'Jack Daniel\'s Tennessee Whiskey',
      'Johnnie Walker Blue Label',
      'Buffalo Trace Bourbon',
      'Blanton\'s Single Barrel',
      'Pappy Van Winkle',
      'Macallan Single Malt Scotch',
      'Balvenie DCS Compendium',
      'Karuizawa Japanese Whisky',
      'Yamazaki 18 and 25 Mizunara',
      'Hakushu Single Malt',
      'Hibiki Harmony',
      'Eagle Rare Bourbon',
      'Weller Bourbon',
      'Colonel E.H. Taylor',
      'Michter\'s Celebration',
      'Glencairn Crystal Glassware',
      'Port Ellen Ghost Distilleries',
    ],
    areaServed: [
      'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 
      'DE', 'GR', 'HU', 'IE', 'IT', 'LV', 'LT', 'LU', 'MT', 'NL', 
      'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE', 'GB', 'CH', 'NO', 'US', 'JP'
    ],
    sameAs: [
      'https://instagram.com/whiskeyeurope',
      'https://facebook.com/whiskeyeurope',
      'https://trustpilot.com/review/whiskeyeurope.org',
    ],
  };

  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="PhoanpLbqcsYTQ2kraJh2NLn0rx1iqHqBpWiqrPt0Mk"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
        />
      </head>
      <body suppressHydrationWarning>
        {children}
        <SalesNotification />
        <TawkToChat />
      </body>
    </html>
  );
}
