export interface KeywordEntry {
  id: string;
  name: string;
  category: 'Irish & Canadian' | 'Tennessee & American' | 'Bourbon & Allocation' | 'Scotch & International' | 'Japanese & Mizunara' | 'Specialty, Casks & Gear';
  brand: string;
  origin: string;
  abv: string;
  tastingNotes: string;
  searchQuery: string;
  tags: string[];
  status: 'In Cellar Stock' | 'Allocated Release' | 'Vault Exclusive' | 'Certified Gear';
}

export const ALL_SEARCH_KEYWORDS: KeywordEntry[] = [
  // 1. Irish & Canadian Whiskies
  {
    id: 'jameson-whiskey',
    name: 'Jameson Whiskey / Jameson Irish Whiskey / Jameson Orange / Jameson Black Barrel',
    category: 'Irish & Canadian',
    brand: 'Jameson',
    origin: 'Midleton Distillery, Cork, Ireland',
    abv: '40% - 43% ABV',
    tastingNotes: 'Triple-distilled smoothness, sweet pot still spice, charred oak sweetness, and vibrant zesty citrus in the Orange release.',
    searchQuery: 'Jameson',
    tags: ['Jameson Whiskey', 'Jameson Irish Whiskey', 'Jameson Orange', 'Jameson Black Barrel', 'Irish Whiskey', 'Triple Distilled', 'Midleton'],
    status: 'In Cellar Stock',
  },
  {
    id: 'redbreast-single-pot-still',
    name: 'Redbreast Single Pot Still Irish Whiskey (12, 15, 21, 27 Year)',
    category: 'Irish & Canadian',
    brand: 'Redbreast',
    origin: 'Midleton Distillery, County Cork, Ireland',
    abv: '40% - 53.5% ABV',
    tastingNotes: 'The quintessential single pot still Irish whiskey, boasting heavy Oloroso sherry cask richness, toasted nuts, dried figs, and warm baking spices.',
    searchQuery: 'Redbreast',
    tags: ['Redbreast Single Pot Still Irish Whiskey', 'Redbreast 12', 'Redbreast 21', 'Redbreast 27', 'Irish Single Pot Still'],
    status: 'In Cellar Stock',
  },
  {
    id: 'green-spot-single-pot-still',
    name: 'Green Spot Single Pot Still Irish Whiskey',
    category: 'Irish & Canadian',
    brand: 'Green Spot (Mitchell & Son)',
    origin: 'Midleton Distillery, Ireland',
    abv: '40% ABV',
    tastingNotes: 'Crisp green apples, fresh barley grain, toasted French oak, cloves, and sweet vanilla cream finish.',
    searchQuery: 'Green Spot',
    tags: ['Green Spot Single Pot Still Irish Whiskey', 'Yellow Spot', 'Red Spot', 'Mitchell & Son Irish Whiskey'],
    status: 'In Cellar Stock',
  },
  {
    id: 'proper-no-twelve',
    name: 'Proper No. Twelve Irish Whiskey',
    category: 'Irish & Canadian',
    brand: 'Proper No. Twelve',
    origin: 'County Antrim / Dublin, Ireland',
    abv: '40% ABV',
    tastingNotes: 'Ultra-smooth grain and single malt blend aged in bourbon barrels with hints of vanilla, honeyed pear, and toasted white oak.',
    searchQuery: 'Proper No. Twelve',
    tags: ['Proper No. Twelve Irish Whiskey', 'Proper 12', 'Conor McGregor Whiskey', 'Irish Blended Whiskey'],
    status: 'In Cellar Stock',
  },
  {
    id: 'bushmills-irish-whiskey',
    name: 'Bushmills Irish Whiskey (Original, Black Bush, 10Y, 16Y, 21Y Single Malt)',
    category: 'Irish & Canadian',
    brand: 'Bushmills',
    origin: 'Old Bushmills Distillery, Northern Ireland (Est. 1608)',
    abv: '40% - 46% ABV',
    tastingNotes: 'Rich honeyed malt, dark fruit sherry maturation, ripe peach, toffee, and a delicate warming peppery finish.',
    searchQuery: 'Bushmills',
    tags: ['Bushmills Irish Whiskey', 'Bushmills 16', 'Bushmills 21', 'Black Bush', 'Old Bushmills Distillery'],
    status: 'In Cellar Stock',
  },
  {
    id: 'crown-royal-canadian-whisky',
    name: 'Crown Royal Canadian Whisky (Deluxe, Black, Northern Harvest Rye, XR)',
    category: 'Irish & Canadian',
    brand: 'Crown Royal',
    origin: 'Gimli Distillery, Manitoba, Canada',
    abv: '40% - 45% ABV',
    tastingNotes: 'Rich creamy vanilla, caramel, dried apricot, baking spices, and exceptionally smooth oak finish.',
    searchQuery: 'Crown Royal',
    tags: ['Crown Royal Canadian Whisky', 'Crown Royal Northern Harvest Rye', 'Crown Royal XR', 'Canadian Whisky'],
    status: 'In Cellar Stock',
  },
  {
    id: 'black-velvet-canadian-whisky',
    name: 'Black Velvet Canadian Whisky',
    category: 'Irish & Canadian',
    brand: 'Black Velvet',
    origin: 'Lethbridge, Alberta, Canada',
    abv: '40% ABV',
    tastingNotes: 'Silky smooth grain profile with light corn sweetness, caramel, butterscotch, and clean oak.',
    searchQuery: 'Black Velvet',
    tags: ['Black Velvet Canadian Whisky', 'Black Velvet Reserve', 'Canadian Blended Whisky'],
    status: 'In Cellar Stock',
  },

  // 2. Tennessee & Iconic American Whiskeys
  {
    id: 'jack-daniels-whiskey',
    name: 'Jack Daniel\'s Whiskey / Tennessee Whiskey / Tennessee Honey / Gentleman Jack / Old No. 7 / Sinatra Select',
    category: 'Tennessee & American',
    brand: 'Jack Daniel\'s',
    origin: 'Lynchburg, Tennessee, United States',
    abv: '35% - 45% ABV',
    tastingNotes: 'Charcoal sugar maple mellowing, toasted marshmallow, banana bread, sweet molasses, and charred American oak.',
    searchQuery: 'Jack Daniel',
    tags: ['Jack Daniel\'s Whiskey', 'Tennessee Whiskey', 'Tennessee Honey', 'Gentleman Jack', 'Old No. 7', 'Jack Daniels Single Barrel', 'Sinatra Select'],
    status: 'In Cellar Stock',
  },
  {
    id: 'uncle-nearest-whiskey',
    name: 'Uncle Nearest Premium Whiskey (1884 Small Batch / 1856 Premium Aged)',
    category: 'Tennessee & American',
    brand: 'Uncle Nearest',
    origin: 'Shelbyville, Tennessee, United States',
    abv: '46.5% - 50% ABV',
    tastingNotes: 'Rich buttered popcorn, maple syrup, nutmeg, dark raisins, caramelized orchard fruits, and cinnamon warmth.',
    searchQuery: 'Uncle Nearest',
    tags: ['Uncle Nearest Premium Whiskey', 'Uncle Nearest 1856', 'Uncle Nearest 1884', 'Tennessee Whiskey Nathan Green'],
    status: 'In Cellar Stock',
  },
  {
    id: 'jim-beam-bourbon',
    name: 'Jim Beam Bourbon Whiskey (White Label, Black Extra-Aged, Double Oak)',
    category: 'Tennessee & American',
    brand: 'Jim Beam',
    origin: 'Clermont, Kentucky, United States',
    abv: '40% - 43% ABV',
    tastingNotes: 'Classic Kentucky straight bourbon with sweet corn, vanilla bean, toasted caramel, and gentle charred oak spice.',
    searchQuery: 'Jim Beam',
    tags: ['Jim Beam Bourbon Whiskey', 'Jim Beam Black', 'Jim Beam Double Oak', 'Kentucky Straight Bourbon'],
    status: 'In Cellar Stock',
  },
  {
    id: 'evan-williams-bourbon',
    name: 'Evan Williams Kentucky Straight Bourbon Whiskey (Black Label, Bottled-in-Bond 100 Proof, Single Barrel)',
    category: 'Tennessee & American',
    brand: 'Evan Williams (Heaven Hill)',
    origin: 'Bardstown, Kentucky, United States',
    abv: '43% - 50% ABV',
    tastingNotes: 'Deep amber color, rich mint, vanilla custard, toffee, brown sugar, and toasted oak.',
    searchQuery: 'Evan Williams',
    tags: ['Evan Williams Kentucky Straight Bourbon Whiskey', 'Evan Williams Single Barrel', 'Evan Williams Bottled in Bond'],
    status: 'In Cellar Stock',
  },
  {
    id: 'traveller-whiskey',
    name: 'Traveller Whiskey (Buffalo Trace / Chris Stapleton Blend No. 40)',
    category: 'Tennessee & American',
    brand: 'Traveller Whiskey',
    origin: 'Buffalo Trace Distillery, Frankfort, Kentucky',
    abv: '45% ABV (90 Proof)',
    tastingNotes: 'Crafted in collaboration with 10x Grammy winner Chris Stapleton & Master Distiller Harlen Wheatley. Notes of vanilla, shortbread cookies, ginger, honey, and toasted oak.',
    searchQuery: 'Traveller Whiskey',
    tags: ['Traveller Whiskey', 'Buffalo Trace Chris Stapleton', 'Traveller Blend No 40', 'American Blended Whiskey'],
    status: 'In Cellar Stock',
  },
  {
    id: 'sirdavis-american-whisky',
    name: 'SirDavis American Whisky (Beyoncé Knowles-Carter & Moët Hennessy)',
    category: 'Tennessee & American',
    brand: 'SirDavis',
    origin: 'Houston, Texas / Indiana / Kentucky Mash',
    abv: '44% ABV (88 Proof)',
    tastingNotes: '51% Rye and 49% Malted Barley finished in Pedro Ximénez sherry casks. Flavors of Seville orange marmalade, sun-dried raisins, baking cloves, and velvety malt.',
    searchQuery: 'SirDavis',
    tags: ['SirDavis American Whisky', 'SirDavis Beyonce', 'Moet Hennessy Whiskey', 'Sir Davis Rye Malt'],
    status: 'In Cellar Stock',
  },
  {
    id: 'stranahans-colorado-whiskey',
    name: 'Stranahan\'s Colorado Whiskey (Original Single Malt, Diamond Peak, Mountain Angel)',
    category: 'Tennessee & American',
    brand: 'Stranahan\'s',
    origin: 'Denver, Colorado, Rocky Mountains',
    abv: '47% ABV (94 Proof)',
    tastingNotes: '100% malted barley mashed with Rocky Mountain snowmelt. Warm butterscotch, maple syrup, leather, and dark chocolate malt.',
    searchQuery: 'Stranahan',
    tags: ['Stranahan\'s Colorado Whiskey', 'American Single Malt', 'Stranahan Diamond Peak'],
    status: 'In Cellar Stock',
  },
  {
    id: 'tin-cup-american-whiskey',
    name: 'Tin Cup American Whiskey / Tincup 10 Year / Tincup Rye',
    category: 'Tennessee & American',
    brand: 'Tincup',
    origin: 'Colorado / Indiana',
    abv: '42% ABV',
    tastingNotes: 'Bourbon mash style cut with Rocky Mountain spring water. Black pepper, cinnamon, rye spice, and sweet caramel vanilla.',
    searchQuery: 'Tin Cup',
    tags: ['Tin Cup American Whiskey', 'Tincup Mountain Whiskey', 'Tincup 10 Year Bourbon', 'Tincup Rye'],
    status: 'In Cellar Stock',
  },
  {
    id: 'mactasker-whiskey',
    name: 'Mactasker Whiskey & Heritage Cask Blends',
    category: 'Tennessee & American',
    brand: 'Mactasker',
    origin: 'Historic American & Highland Heritage',
    abv: '43% ABV',
    tastingNotes: 'Crisp orchard pears, toasted honey grains, vanilla pod, and balanced oak tannic depth.',
    searchQuery: 'Mactasker',
    tags: ['Mactasker Whiskey', 'Mactasker Heritage Blend', 'Craft Whiskey Europe'],
    status: 'In Cellar Stock',
  },
  {
    id: 'chattanooga-straight-bourbon',
    name: 'Chattanooga Straight Bourbon Whiskey (Tennessee High Malt 91 & Cask 111)',
    category: 'Tennessee & American',
    brand: 'Chattanooga Whiskey',
    origin: 'Chattanooga, Tennessee',
    abv: '45.5% - 55.5% ABV',
    tastingNotes: 'Signature Tennessee High Malt mash bill. Notes of dark chocolate malt, plum jam, charred oak, and spicy espresso bean.',
    searchQuery: 'Chattanooga',
    tags: ['Chattanooga Straight Bourbon Whiskey', 'Chattanooga High Malt 111', 'Chattanooga Cask 91'],
    status: 'In Cellar Stock',
  },

  // 3. Kentucky Straight Bourbons & Rare Allocations
  {
    id: 'buffalo-trace-bourbon',
    name: 'Buffalo Trace Kentucky Straight Bourbon / Buffalo Trace Bourbon Cream',
    category: 'Bourbon & Allocation',
    brand: 'Buffalo Trace',
    origin: 'Frankfort, Kentucky, United States',
    abv: '40% - 45% ABV',
    tastingNotes: 'Rich complex aromas of vanilla, mint, and molasses. The palate is pleasantly sweet with brown sugar, spice, oak, and toffee.',
    searchQuery: 'Buffalo Trace',
    tags: ['Buffalo Trace Kentucky Straight Bourbon', 'Buffalo Trace Bourbon Cream', 'Buffalo Trace Distillery', 'Frankfort Kentucky'],
    status: 'In Cellar Stock',
  },
  {
    id: 'blantons-single-barrel-bourbon',
    name: 'Blanton\'s Single Barrel Bourbon Whiskey (Original, Gold Edition, Straight From The Barrel)',
    category: 'Bourbon & Allocation',
    brand: 'Blanton\'s',
    origin: 'Warehouse H, Buffalo Trace Distillery, Kentucky',
    abv: '46.5% - 65% ABV',
    tastingNotes: 'The world\'s first single barrel bourbon. Sweet citrus, burnt orange peel, caramel, vanilla, rye spice, and polished oak.',
    searchQuery: 'Blanton',
    tags: ['Blanton\'s Single Barrel Bourbon Whiskey', 'Blantons Gold Edition', 'Blantons Straight From The Barrel', 'Warehouse H Buffalo Trace'],
    status: 'Allocated Release',
  },
  {
    id: 'eagle-rare-bourbon',
    name: 'Eagle Rare 10 Year / 12 Year / 25 Year Kentucky Straight Bourbon Whiskey',
    category: 'Bourbon & Allocation',
    brand: 'Eagle Rare',
    origin: 'Buffalo Trace Distillery, Kentucky',
    abv: '45% - 50.5% ABV',
    tastingNotes: 'Complex aromas of toffee, hints of orange peel, herbs, honey, leather, and oak. Bold, dry, and delicate oak finish.',
    searchQuery: 'Eagle Rare',
    tags: ['Eagle Rare 10 Year', 'Eagle Rare 12 Year Kentucky Straight Bourbon Whiskey', 'Eagle Rare 25 Year Old', 'Double Eagle Very Rare 20 Year'],
    status: 'Vault Exclusive',
  },
  {
    id: 'pappy-van-winkle-bourbon',
    name: 'Pappy Van Winkle / Old Rip Van Winkle Bourbon (10, 12 Lot B, 15, 20, 23, 25 Year)',
    category: 'Bourbon & Allocation',
    brand: 'Pappy Van Winkle',
    origin: 'Stitzel-Weller / Buffalo Trace Distillery, Kentucky',
    abv: '45.2% - 53.5% ABV',
    tastingNotes: 'The holy grail of wheated bourbon. Decadent caramel, dark roasted pecans, sweet pipe tobacco, dark cherries, and ancient varnished oak.',
    searchQuery: 'Pappy Van Winkle',
    tags: ['Pappy Van Winkle Bourbon', 'Old Rip Van Winkle Bourbon', 'Pappy Van Winkle 15 Year', 'Pappy Van Winkle 20 Year', 'Pappy Van Winkle 23 Year', 'Old Rip Van Winkle 25 Year'],
    status: 'Vault Exclusive',
  },
  {
    id: 'weller-straight-bourbon',
    name: 'Weller Straight Bourbon (Special Reserve / 12 Year / Full Proof / C.Y.P.B. / Daniel Weller Spelt Wheat / Millennium)',
    category: 'Bourbon & Allocation',
    brand: 'W.L. Weller',
    origin: 'Buffalo Trace Distillery, Kentucky',
    abv: '45% - 57% ABV',
    tastingNotes: 'The original wheated bourbon substitute for rye. Sweet honey, vanilla blossom, caramel apple, cinnamon bread, and smooth creamy oak.',
    searchQuery: 'Weller',
    tags: ['Weller Straight Bourbon', 'Weller Special Reserve', 'Weller 12 Year', 'Daniel Weller Spelt Wheat', 'W.L. Weller Millennium', 'Weller Full Proof'],
    status: 'Allocated Release',
  },
  {
    id: 'colonel-eh-taylor',
    name: 'Colonel E.H. Taylor Small Batch Bourbon (Single Barrel, Barrel Proof, Cured Oak, Tornado Surviving, Straight Rye)',
    category: 'Bourbon & Allocation',
    brand: 'Colonel E.H. Taylor, Jr.',
    origin: 'Old Fashioned Copper / Buffalo Trace Distillery, Kentucky',
    abv: '50% (100 Proof Bottled in Bond)',
    tastingNotes: 'Caramel corn sweetness, butterscotch, licorice, spicy rye kick, pepper, and lingering leather tobacco.',
    searchQuery: 'Colonel E H Taylor',
    tags: ['Colonel E.H. Taylor Small Batch Bourbon', 'Colonel E H Taylor Cured Oak', 'Colonel E H Taylor Warehouse C Tornado Surviving', 'Bottled in Bond Bourbon'],
    status: 'Allocated Release',
  },
  {
    id: 'george-t-stagg',
    name: 'George T. Stagg Straight Bourbon Whiskey & Stagg / Stagg Jr.',
    category: 'Bourbon & Allocation',
    brand: 'Stagg (Buffalo Trace Antique Collection)',
    origin: 'Buffalo Trace Distillery, Kentucky',
    abv: '58% - 69% Barrel Proof',
    tastingNotes: 'Unfiltered, uncut titan. Lush dark chocolate, molasses, espresso, pipe tobacco, black cherries, and roaring oak spices.',
    searchQuery: 'George T Stagg',
    tags: ['George T. Stagg Straight Bourbon Whiskey', 'Stagg Straight Bourbon Whiskey', 'Stagg Jr.', 'BTAC Antique Collection'],
    status: 'Vault Exclusive',
  },
  {
    id: 'basil-haydens-bourbon',
    name: 'Basil Hayden\'s Bourbon Whiskey (Straight Bourbon, Dark Rye, 10 Year)',
    category: 'Bourbon & Allocation',
    brand: 'Basil Hayden',
    origin: 'Jim Beam Small Batch, Clermont, Kentucky',
    abv: '40% ABV',
    tastingNotes: 'High-rye recipe delivering spicy peppery warmth, honey, tea leaves, charred oak, and crisp citrus zest.',
    searchQuery: 'Basil Hayden',
    tags: ['Basil Hayden\'s Bourbon Whiskey', 'Basil Hayden Dark Rye', 'Basil Hayden 10 Year', 'High Rye Bourbon'],
    status: 'In Cellar Stock',
  },
  {
    id: 'woodford-reserve-bourbon',
    name: 'Woodford Reserve Straight Bourbon / Double Oaked Bourbon / Master\'s Collection',
    category: 'Bourbon & Allocation',
    brand: 'Woodford Reserve',
    origin: 'Versailles, Kentucky, United States',
    abv: '43.2% - 45.2% ABV',
    tastingNotes: 'Copper pot distilled. Dried fruit, mint, oranges, rich cocoa, vanilla, and heavy toasted oak from dual-barrel finishing.',
    searchQuery: 'Woodford Reserve',
    tags: ['Woodford Reserve Straight Bourbon', 'Woodford Reserve Double Oaked Bourbon', 'Woodford Reserve Master Collection'],
    status: 'In Cellar Stock',
  },
  {
    id: 'angels-envy-bourbon',
    name: 'Angel\'s Envy Bourbon Whiskey (Port Wine Cask Finish & Cask Strength)',
    category: 'Bourbon & Allocation',
    brand: 'Angel\'s Envy (Lincoln Henderson)',
    origin: 'Louisville, Kentucky',
    abv: '43.3% - 60% ABV',
    tastingNotes: 'Finished in 60-year-old Portuguese ruby port wine casks. Vanilla, ripe berries, candied tangerines, dark chocolate, and toasted nuts.',
    searchQuery: 'Angel\'s Envy',
    tags: ['Angel\'s Envy Bourbon Whiskey', 'Angels Envy Port Finish', 'Angels Envy Cask Strength', 'Lincoln Henderson Bourbon'],
    status: 'In Cellar Stock',
  },
  {
    id: 'bookers-bourbon',
    name: 'Booker\'s Bourbon Whiskey (Uncut & Unfiltered Small Batch Collection)',
    category: 'Bourbon & Allocation',
    brand: 'Booker\'s',
    origin: 'Boston, Kentucky (Jim Beam Master Cellar)',
    abv: '60% - 64% Barrel Strength',
    tastingNotes: 'Raw powerhouse flavor. Intense caramel, toasted vanilla bean, char, mocha, roasted nuts, and warm baking spices.',
    searchQuery: 'Booker',
    tags: ['Booker\'s Bourbon Whiskey', 'Bookers Small Batch', 'Bookers Uncut Unfiltered', 'Jim Beam Booker Noe'],
    status: 'Allocated Release',
  },
  {
    id: 'michters-bourbon',
    name: 'Michter\'s Straight Bourbon / 10 Year Bourbon / 25 Year Single Barrel / Celebration Sour Mash',
    category: 'Bourbon & Allocation',
    brand: 'Michter\'s',
    origin: 'Louisville, Kentucky',
    abv: '45.7% - 57.2% ABV',
    tastingNotes: 'Rich dried stone fruits, vanilla custard, smoky charred oak, candied orange peel, and dark chocolate truffles.',
    searchQuery: 'Michter',
    tags: ['Michter\'s Straight Bourbon', 'Michter\'s 10 Year Bourbon', 'Michters 25 Year Old Single Barrel Bourbon', 'Michters Celebration Sour Mash'],
    status: 'Vault Exclusive',
  },
  {
    id: 'elijah-craig-bourbon',
    name: 'Elijah Craig Small Batch / Barrel Strength / 18 Year Single Barrel / 23 Year Bourbon',
    category: 'Bourbon & Allocation',
    brand: 'Elijah Craig (Heaven Hill)',
    origin: 'Bardstown, Kentucky',
    abv: '47% - 68% ABV',
    tastingNotes: 'Honoring the father of bourbon. Warm nutmeg, smoke, deep molasses, sweet corn, vanilla custard, and massive charred wood tannin.',
    searchQuery: 'Elijah Craig',
    tags: ['Elijah Craig Small Batch', 'Elijah Craig Barrel Strength', 'Elijah Craig 18 Year Bourbon', 'Heaven Hill Elijah Craig'],
    status: 'Allocated Release',
  },
  {
    id: 'four-roses-bourbon',
    name: 'Four Roses Kentucky Straight Bourbon (Small Batch, Single Barrel, Small Batch Select, Limited Edition 135th)',
    category: 'Bourbon & Allocation',
    brand: 'Four Roses',
    origin: 'Lawrenceburg, Kentucky',
    abv: '45% - 54% ABV',
    tastingNotes: '10 unique proprietary recipes combining 2 mash bills and 5 yeast strains. Ripe red berries, floral honeysuckle, spice, and mellow oak.',
    searchQuery: 'Four Roses',
    tags: ['Four Roses Kentucky Straight Bourbon', 'Four Roses Single Barrel', 'Four Roses Small Batch Select', 'Four Roses Limited Edition'],
    status: 'In Cellar Stock',
  },
  {
    id: 'wild-turkey-bourbon',
    name: 'Wild Turkey Bourbon / Wild Turkey 101 Bourbon / Rare Breed / Master\'s Keep',
    category: 'Bourbon & Allocation',
    brand: 'Wild Turkey (Jimmy & Eddie Russell)',
    origin: 'Lawrenceburg, Kentucky',
    abv: '40.5% - 58.4% ABV',
    tastingNotes: 'Deep No. 4 alligator char barrels deliver bold vanilla, caramel, rye spice, black pepper, and honeyed orange peel.',
    searchQuery: 'Wild Turkey',
    tags: ['Wild Turkey Bourbon', 'Wild Turkey 101 Bourbon', 'Wild Turkey Rare Breed', 'Wild Turkey Masters Keep'],
    status: 'In Cellar Stock',
  },
  {
    id: 'makers-mark-bourbon',
    name: 'Maker\'s Mark Straight Bourbon / Maker\'s 46 Bourbon Whisky / Cask Strength / Wood Finishing Series',
    category: 'Bourbon & Allocation',
    brand: 'Maker\'s Mark',
    origin: 'Loretto, Kentucky',
    abv: '45% - 55% ABV',
    tastingNotes: 'Red winter wheat mash bill hand-dipped in red wax. Soft sweet caramel, vanilla, spiced cherry, and French oak staves in Maker\'s 46.',
    searchQuery: 'Maker\'s Mark',
    tags: ['Maker\'s Mark Straight Bourbon', 'Maker\'s 46 Bourbon Whisky', 'Makers Mark Cask Strength', 'Wheated Kentucky Bourbon'],
    status: 'In Cellar Stock',
  },
  {
    id: 'bulleit-bourbon-rye',
    name: 'Bulleit Straight Bourbon / Bulleit Rye Whiskey / 10 Year Old',
    category: 'Bourbon & Allocation',
    brand: 'Bulleit Frontier Whiskey',
    origin: 'Shelbyville, Kentucky',
    abv: '45% ABV (90 Proof)',
    tastingNotes: 'Frontier style high-rye mash. Spicy peppery bite, sweet oak, nutmeg, toffee, dried fruit, and clean crisp finish.',
    searchQuery: 'Bulleit',
    tags: ['Bulleit Straight Bourbon', 'Bulleit Rye Whiskey', 'Bulleit 10 Year', 'Frontier Whiskey'],
    status: 'In Cellar Stock',
  },
  {
    id: 'knob-creek-bourbon',
    name: 'Knob Creek 9 / 12 / 15 / 18 / 21 Kentucky Straight Bourbon Whiskey',
    category: 'Bourbon & Allocation',
    brand: 'Knob Creek',
    origin: 'Clermont, Kentucky',
    abv: '50% ABV (100 Proof)',
    tastingNotes: 'Big, full-bodied bourbon aged in deeply charred American oak. Maple sugar, toasted nuts, vanilla, and lingering spicy smoke.',
    searchQuery: 'Knob Creek',
    tags: ['Knob Creek 9', 'Knob Creek 12', 'Knob Creek 21 Kentucky Straight Bourbon Whiskey', 'Knob Creek 15', 'Knob Creek 18'],
    status: 'Allocated Release',
  },
  {
    id: 'king-of-kentucky',
    name: 'King of Kentucky Straight Bourbon (14 - 18 Year Single Barrel)',
    category: 'Bourbon & Allocation',
    brand: 'King of Kentucky (Brown-Forman)',
    origin: 'Louisville, Kentucky',
    abv: '62% - 66% Barrel Strength',
    tastingNotes: 'Ultra-rare single barrel release. Ancient mahogany, molten dark caramel, leather, tobacco leaf, and espresso chocolate.',
    searchQuery: 'King of Kentucky',
    tags: ['King of Kentucky Straight Bourbon', 'King of Kentucky 18 Year Single Barrel Bourbon', 'Brown-Forman Rare Bourbon'],
    status: 'Vault Exclusive',
  },
  {
    id: 'blood-oath-bourbon',
    name: 'Blood Oath Bourbon Pact (Pact No. 1 through Pact No. 10)',
    category: 'Bourbon & Allocation',
    brand: 'Blood Oath (Lux Row)',
    origin: 'Bardstown, Kentucky',
    abv: '49.3% ABV (98.6 Proof)',
    tastingNotes: 'A clandestine master blend of three Kentucky straight bourbons finished in exotic casks like Cognac, Cabernet, and Calvados.',
    searchQuery: 'Blood Oath',
    tags: ['Blood Oath Bourbon Pact', 'Blood Oath Pact 9', 'Blood Oath Pact 10', 'Lux Row Distillers'],
    status: 'Allocated Release',
  },
  {
    id: 'old-fitzgerald-bourbon',
    name: 'Old Fitzgerald Bottled in Bond Bourbon (Decanter Series 8Y to 19Y)',
    category: 'Bourbon & Allocation',
    brand: 'Old Fitzgerald (Heaven Hill)',
    origin: 'Bardstown, Kentucky',
    abv: '50% (100 Proof Bottled in Bond)',
    tastingNotes: 'Stunning vintage glass decanter. Wheated recipe offering sweet butterscotch, orchard fruit pie, nutmeg, and polished oak.',
    searchQuery: 'Old Fitzgerald',
    tags: ['Old Fitzgerald Bottled in Bond Bourbon', 'Very Very Old Fitzgerald Bottled in Bond', 'Old Fitz Decanter Series'],
    status: 'Vault Exclusive',
  },
  {
    id: 'old-forester-birthday-bourbon',
    name: 'Old Forester Bourbon / Birthday Bourbon / 1910 / 1920 Prohibition Style',
    category: 'Bourbon & Allocation',
    brand: 'Old Forester',
    origin: 'Louisville, Kentucky',
    abv: '43% - 57.5% ABV',
    tastingNotes: 'America\'s first bottled bourbon. Rich dark chocolate, caramelized banana, toasted marshmallow, cherry cordial, and robust oak.',
    searchQuery: 'Old Forester',
    tags: ['Old Forester Bourbon', 'Old Forester Birthday Bourbon', 'Old Forester 1920', 'Old Forester 1910'],
    status: 'Allocated Release',
  },
  {
    id: 'other-kentucky-bourbons',
    name: 'Craft & Small Batch Bourbons: 1792 (Barton), Bardstown, Calumet Farm, Castle & Key, Dettling 1867, Doc Holliday, Elmer T. Lee, Frank August, Frey Ranch, Garrison Brothers, Green River, Heaven Hill, Horse Soldier, Larceny, New Riff, Old Crow, Old Grand-Dad, Peerless, Penelope, Pinhook, Rabbit Hole, Redemption, Redwood Empire, Rock Hill Farms, Russell\'s Reserve, Smoke Wagon, Still Austin, Widow Jane 10Y, Wolcott, Woodinville, Yellowstone, A. Smith Bowman, Ancient Age, Benchmark, Bib & Tucker, Blade and Bow, Blue Run, Brother\'s Bond, Chicken Cock',
    category: 'Bourbon & Allocation',
    brand: 'Kentucky & American Craft Bourbon Index',
    origin: 'Kentucky, Texas, Indiana, Nevada, Alabama, New York',
    abv: '45% - 60% ABV',
    tastingNotes: 'Master index of exceptional small-batch and single-barrel bourbons featuring high-rye, wheated, and barrel-proof profiles.',
    searchQuery: 'Bourbon',
    tags: [
      '1792 Small Batch Bourbon', 'Barton 1792', 'Bardstown Bourbon', 'Calumet Farm Single Rack Black Bourbon',
      'Castle & Key Small Batch Bourbon', 'Dettling 1867 Straight Bourbon', 'Doc Holliday Straight Bourbon',
      'Elmer T. Lee Single Barrel Bourbon', 'Frank August Small Batch Bourbon', 'Frey Ranch Straight Bourbon',
      'Garrison Brothers Texas Straight Bourbon', 'Green River Straight Bourbon', 'Green River Wheated Bourbon',
      'Heaven Hill Straight Bourbon', 'Horse Soldier Straight Bourbon', 'Larceny Very Special Small Batch Bourbon',
      'New Riff Kentucky Straight Bourbon', 'Old Crow Straight Bourbon', 'Old Grand-Dad Bourbon',
      'Peerless Small Batch Bourbon', 'Penelope Straight Bourbon', 'Pinhook Straight Bourbon',
      'Rabbit Hole Straight Bourbon', 'Redemption Straight Bourbon', 'Redwood Empire Straight Bourbon',
      'Rock Hill Farms Single Barrel Bourbon', 'Russell\'s Reserve Straight Bourbon', 'Smoke Wagon Straight Bourbon',
      'Still Austin Straight Bourbon', 'Widow Jane 10 Year Straight Bourbon', 'Wolcott Kentucky Straight Bourbon',
      'Woodinville Straight Bourbon', 'Yellowstone Select Kentucky Straight Bourbon', 'A. Smith Bowman Cask Strength Bourbon',
      'Ancient Age Straight Bourbon', 'Benchmark Kentucky Straight Bourbon', 'Bib & Tucker Small Batch Bourbon',
      'Blade and Bow Kentucky Straight Bourbon', 'Blue Run Straight Bourbon', 'Brother\'s Bond Straight Bourbon',
      'Chicken Cock Kentucky Straight Bourbon', 'Willett Straight Bourbon'
    ],
    status: 'In Cellar Stock',
  },

  // 4. Rye & High-Rye Artisan Whiskies
  {
    id: 'whistlepig-rye-whiskey',
    name: 'WhistlePig Rye Whiskey (10 Year Small Batch, 12 Year Old World Cask, 15 Year Estate Oak, Boss Hog)',
    category: 'Tennessee & American',
    brand: 'WhistlePig',
    origin: 'Shoreham, Vermont, United States',
    abv: '50% - 60% ABV',
    tastingNotes: '100% rye mash aged in bespoke Vermont estate oak. Explosive allspice, orange peel, ginger, clove, caramel, and mint.',
    searchQuery: 'WhistlePig',
    tags: ['WhistlePig Rye Whiskey', 'WhistlePig 10 Year', 'WhistlePig 12 Year', 'WhistlePig Boss Hog', 'Vermont Estate Rye'],
    status: 'Allocated Release',
  },
  {
    id: 'sazerac-straight-rye',
    name: 'Sazerac Straight Rye Whiskey & Sazerac 18 Year (Buffalo Trace Antique Collection)',
    category: 'Tennessee & American',
    brand: 'Sazerac',
    origin: 'New Orleans / Buffalo Trace, Kentucky',
    abv: '45% - 45% ABV',
    tastingNotes: 'The definitive New Orleans cocktail rye. Sweet aromas of candied spices, citrus, licorice, pepper, and clean dry oak.',
    searchQuery: 'Sazerac',
    tags: ['Sazerac Straight Rye Whiskey', 'Sazerac 18 Year', 'Buffalo Trace Sazerac', 'New Orleans Rye'],
    status: 'Allocated Release',
  },
  {
    id: 'high-west-whiskey',
    name: 'High West Bourbon / Whiskey (Campfire, Rendezvous Rye, Double Rye, A Midwinter Night\'s Dram)',
    category: 'Tennessee & American',
    brand: 'High West Distillery',
    origin: 'Park City, Utah, Wasatch Range',
    abv: '46% - 49.3% ABV',
    tastingNotes: 'Pioneering blends of straight rye and peated single malt. Campfire smoke, cinnamon honey buns, dark cherry syrup, and spice.',
    searchQuery: 'High West',
    tags: ['High West Bourbon', 'High West Whiskey', 'High West Rendezvous Rye', 'High West A Midwinter Nights Dram', 'High West Campfire'],
    status: 'In Cellar Stock',
  },
  {
    id: 'tx-blended-whiskey',
    name: 'TX Blended Whiskey / TX Straight Bourbon (Firestone & Robertson)',
    category: 'Tennessee & American',
    brand: 'TX Whiskey',
    origin: 'Whiskey Ranch, Fort Worth, Texas',
    abv: '41% - 45% ABV',
    tastingNotes: 'Proprietary wild pecan yeast strain. Honey butter, dark fruit, sweet Texas corn, and warm toasted oak.',
    searchQuery: 'TX Whiskey',
    tags: ['TX Blended Whiskey', 'TX Straight Bourbon', 'Firestone and Robertson Whiskey', 'Texas Bourbon'],
    status: 'In Cellar Stock',
  },
  {
    id: 'blackened-american-whiskey',
    name: 'Blackened American Whiskey (Metallica & Dave Pickerell / Black Noise Sound Aging)',
    category: 'Tennessee & American',
    brand: 'Blackened',
    origin: 'Sweet Amber Distilling, United States',
    abv: '45% ABV (90 Proof)',
    tastingNotes: 'Sonic-enhancement using Metallica tracks to agitate black brandy casks. Notes of burnt caramel, honey, apricot, cinnamon, and spiced wood.',
    searchQuery: 'Blackened',
    tags: ['Blackened American Whiskey', 'Metallica Whiskey', 'Dave Pickerell Blackened', 'Black Noise Sonic Aging'],
    status: 'In Cellar Stock',
  },

  // 5. Scotch Whiskies & World Single Malts
  {
    id: 'macallan-scotch-whisky',
    name: 'Macallan Single Malt Scotch Whisky (Sherry Oak 12/18/25/30, Double Cask, The Red Collection 50Y, Folio Series, Horizon)',
    category: 'Scotch & International',
    brand: 'The Macallan',
    origin: 'Easter Elchies House, Craigellachie, Speyside, Scotland',
    abv: '40% - 52% ABV',
    tastingNotes: '100% natural color from handcrafted Jerez sherry-seasoned oak casks. Dried sultanas, orange marmalade, ginger, cinnamon, and velvety chocolate.',
    searchQuery: 'Macallan',
    tags: ['Macallan Single Malt Scotch Whisky', 'The Macallan 25 Year Old Sherry Oak', 'The Macallan 30 Year Old Sherry Oak', 'The Macallan 50 Year Old The Red Collection', 'The Archival Series Folio 2'],
    status: 'Vault Exclusive',
  },
  {
    id: 'johnnie-walker-scotch',
    name: 'Johnnie Walker Blue Label / Black Label / Red Label / Ghost & Rare Port Ellen',
    category: 'Scotch & International',
    brand: 'Johnnie Walker',
    origin: 'Kilmarnock / Edinburgh, Scotland',
    abv: '40% - 43.8% ABV',
    tastingNotes: 'Master blend of Scotland\'s rarest single malts including ghost distilleries. Hazelnuts, honey, rose petals, zesty orange, and whisper of peat smoke.',
    searchQuery: 'Johnnie Walker',
    tags: ['Johnnie Walker Blue Label', 'Johnnie Walker Black Label', 'Johnnie Walker Red Label', 'Johnnie Walker Blue Label Ghost and Rare Port Ellen'],
    status: 'In Cellar Stock',
  },
  {
    id: 'monkey-shoulder-scotch',
    name: 'Monkey Shoulder Scotch Whisky (Original Triple Malt & Smokey Monkey)',
    category: 'Scotch & International',
    brand: 'Monkey Shoulder (William Grant & Sons)',
    origin: 'Dufftown, Speyside, Scotland',
    abv: '40% ABV',
    tastingNotes: 'A 100% malt whisky blend from Glenfiddich, Balvenie, and Kininvie. Zesty orange, vanilla, honey, and spiced oak.',
    searchQuery: 'Monkey Shoulder',
    tags: ['Monkey Shoulder Scotch Whisky', 'Smokey Monkey', 'William Grant Blended Malt', 'Speyside Triple Malt'],
    status: 'In Cellar Stock',
  },
  {
    id: 'the-dalmore-single-malt',
    name: 'The Dalmore Single Malt Scotch Whisky (12, 15, 18, 21, King Alexander III, 25 Year, Constellation)',
    category: 'Scotch & International',
    brand: 'The Dalmore',
    origin: 'Alness, Highlands, Scotland',
    abv: '40% - 45% ABV',
    tastingNotes: 'Aged in rare Matusalem Oloroso sherry casks from Gonzalez Byass. Seville oranges, dark cacao, Java coffee, cinnamon, and plums.',
    searchQuery: 'The Dalmore',
    tags: ['The Dalmore Single Malt Scotch Whisky', 'Dalmore King Alexander III', 'Dalmore 18', 'Dalmore 21', 'Highland Single Malt'],
    status: 'In Cellar Stock',
  },
  {
    id: 'buchanans-cutty-sark',
    name: 'Buchanan\'s Blended Scotch Whisky & Cutty Sark Blended Scotch Whisky (Prohibition Edition)',
    category: 'Scotch & International',
    brand: 'Buchanan\'s / Cutty Sark',
    origin: 'Scotland',
    abv: '40% - 50% ABV',
    tastingNotes: 'Classic British heritage blends with bright orchard fruits, gentle smoke, vanilla pods, and toasted barley.',
    searchQuery: 'Buchanans',
    tags: ['Buchanan\'s Blended Scotch Whisky', 'Cutty Sark Blended Scotch Whisky', 'Cutty Sark Prohibition', 'Blended Scotch'],
    status: 'In Cellar Stock',
  },
  {
    id: 'indri-indian-whisky',
    name: 'Indri Single Malt Indian Whisky (Trini Three Wood / Dru Cask Strength / Diwali Collector)',
    category: 'Scotch & International',
    brand: 'Indri (Piccadily Distilleries)',
    origin: 'Indri, Haryana, Foothills of Himalayas, India',
    abv: '46% - 57.2% ABV',
    tastingNotes: 'Distilled from six-row Indian barley and aged in ex-Bourbon, French PX Sherry, and ex-Wine barrels. Tropical mango, pineapple, candied ginger, and black tea.',
    searchQuery: 'Indri',
    tags: ['Indri Single Malt Indian Whisky', 'Indri Trini Three Wood', 'Indri Dru Cask Strength', 'Indian Single Malt Whisky'],
    status: 'In Cellar Stock',
  },
  {
    id: 'ballantines-heritage',
    name: 'Ballantine\'s Heritage Scotch (21, 23, 30 Year, 40 Year Chapter 2, Masterclass 40Y)',
    category: 'Scotch & International',
    brand: 'Ballantine\'s',
    origin: 'Dumbarton / Speyside / Highlands, Scotland',
    abv: '40% - 43% ABV',
    tastingNotes: 'Sublime master blending combining rare Miltonduff and Glenburgie single malts with honeyed pear, vanilla, and gentle smoky peat.',
    searchQuery: 'Ballantine',
    tags: ['ballantines 21 year old blended scotch whisky', 'ballantines 30 year old', 'ballantines 40 year old chapter 2 the waiting', 'ballantines masterclass collection 40 year old'],
    status: 'Vault Exclusive',
  },

  // 6. Japanese Whiskies & Mizunara Distilleries
  {
    id: 'yamazaki-single-malt',
    name: 'Yamazaki Japanese Single Malt Whiskey (including Yamazaki 12, 18, 25, 50, Mizunara & Tsukuriwake)',
    category: 'Japanese & Mizunara',
    brand: 'Yamazaki (Suntory)',
    origin: 'Shimamoto, Osaka Prefecture, Japan (Est. 1923)',
    abv: '43% - 48% ABV',
    tastingNotes: 'Japan\'s first single malt distillery. Rare Japanese Mizunara oak delivers sandalwood incense, agarwood, dried persimmon, coconut, and spiced apple.',
    searchQuery: 'Yamazaki',
    tags: ['Yamazaki Japanese Single Malt Whiskey', 'Yamazaki 18', 'Yamazaki 25', 'Yamazaki 50', 'Yamazaki Mizunara Tsukuriwake 2024', 'Yamazaki 1995 Owner\'s Cask'],
    status: 'Vault Exclusive',
  },
  {
    id: 'hakushu-single-malt',
    name: 'Hakushu Japanese Single Malt Whisky (including Hakushu 12, 18, 25 Year Old & Heavily Peated)',
    category: 'Japanese & Mizunara',
    brand: 'Hakushu (Suntory)',
    origin: 'Mount Kaikoma Forest, Yamanashi Prefecture, Japan',
    abv: '43% - 48% ABV',
    tastingNotes: 'The forest mountain distillery. Crisp green apple, mint leaves, cucumber, pine needles, soft peat smoke, and gentle citrus finish.',
    searchQuery: 'Hakushu',
    tags: ['Hakushu Japanese Single Malt Whisky', 'Hakushu 12', 'Hakushu 18', 'Hakushu 25', 'Hakushu Heavily Peated 2013', 'Hakushu Spanish Oak 2021'],
    status: 'Allocated Release',
  },
  {
    id: 'hibiki-japanese-whisky',
    name: 'Hibiki Japanese Harmony Whiskey (12, 17, 21, 30, 35, 40 Year Old & 100th Anniversary)',
    category: 'Japanese & Mizunara',
    brand: 'Hibiki (Suntory)',
    origin: 'Yamazaki / Hakushu / Chita, Japan',
    abv: '43% ABV',
    tastingNotes: '24-faceted crystal bottle symbolizing the 24 seasons (Sekki). White chocolate, rose petals, lychee, rosemary, sandalwood, and Mizunara oak.',
    searchQuery: 'Hibiki',
    tags: ['Hibiki Japanese Harmony Whiskey', 'Hibiki 12 Year Old', 'Hibiki 17 Year Old', 'Hibiki 21 Year Old', 'Hibiki 30 Year Old', 'Hibiki 35 Year Old', 'The Hibiki Aged 40 Years'],
    status: 'Vault Exclusive',
  },
  {
    id: 'karuizawa-ghost-whisky',
    name: 'Karuizawa Ghost Single Casks (1980 Golden Samurai, 1981, 1984, 1986, 1992, Mount Fuji, 30Y Geisha, 48Y 1964)',
    category: 'Japanese & Mizunara',
    brand: 'Karuizawa',
    origin: 'Mount Asama, Nagano, Japan (Closed 2000)',
    abv: '55% - 64% Cask Strength',
    tastingNotes: 'The world\'s most coveted silent ghost distillery. 100% Golden Promise malt aged exclusively in Spanish sherry casks. Smoked cedar, prunes, dark cacao, and incense.',
    searchQuery: 'Karuizawa',
    tags: ['Karuizawa 1980 Golden Samurai', 'Karuizawa 48 Year Old 1964', 'Karuizawa 30 Year Old Geisha', 'Karuizawa Ghost Distillery'],
    status: 'Vault Exclusive',
  },
  {
    id: 'nikka-japanese-whisky',
    name: 'Nikka Japanese Whisky (Nikka From The Barrel / Taketsuru Pure Malt / Yoichi / Miyagikyo)',
    category: 'Japanese & Mizunara',
    brand: 'Nikka (Masataka Taketsuru)',
    origin: 'Yoichi, Hokkaido & Miyagikyo, Sendai, Japan',
    abv: '45% - 51.4% ABV',
    tastingNotes: 'Crafted by the father of Japanese whisky. Bold oak richness, dried apricot, clove, spicy orange zest, and delicate peat smoke.',
    searchQuery: 'Nikka',
    tags: ['Nikka Japanese Whisky', 'Nikka From The Barrel', 'Nikka Taketsuru', 'Miyagikyo 10 year old', 'Miyagikyo 15 year old', 'Yoichi Single Malt'],
    status: 'In Cellar Stock',
  },
  {
    id: 'suntory-toki-chita',
    name: 'Suntory Toki Japanese Whisky & Suntory The Chita Single Grain Whisky',
    category: 'Japanese & Mizunara',
    brand: 'Suntory',
    origin: 'Chita Peninsula / Osaka, Japan',
    abv: '43% ABV',
    tastingNotes: 'Toki brings refreshing green apple, basil, and honey. The Chita delivers delicate sweet grain, cardamom, acacia honey, and clean oak.',
    searchQuery: 'Suntory Toki',
    tags: ['Suntory Toki Japanese Whisky', 'Suntory The Chita Single Grain Whisky', 'Suntory Highball Whisky'],
    status: 'In Cellar Stock',
  },
  {
    id: 'japanese-craft-distilleries',
    name: 'Japanese Craft & Heritage Whiskies: Akashi (White Oak), Chichibu (Taboo & Seven Gods), Fuji Single Malt, Fuyu Small Batch, Hatozaki, Iwai (Mars Shinshu), Kaigan, Kaiyo Mizunara Oak, Kanekou Okinawa, Kikori Rice, Kurayoshi Pure Malt, Kyoto, Maen, Meikakuna, Nobushi, Ryujin, Sadashi, Yamato Armor Takeda Edition',
    category: 'Japanese & Mizunara',
    brand: 'Japanese Master Distillery Index',
    origin: 'Saitama, Nagano, Yamanashi, Hyogo, Okinawa, Kyoto, Shizuoka',
    abv: '40% - 50% ABV',
    tastingNotes: 'Artisanal micro-distilleries showcasing Mizunara cask finishing, pure mountain snowmelt, rice distillation, and hand-forged copper pot stills.',
    searchQuery: 'Japanese',
    tags: [
      'Kaigan Japanese Whisky', 'Kaiyo Mizunara Oak Japanese Whisky', 'Nobushi Japanese Blended Whisky',
      'Akashi Blended Japanese Whisky', 'Akashi White Oak', 'Kikori Japanese Rice Whiskey',
      'Maen Japanese Whisky', 'Fuji Single Malt Japanese Whisky', 'Ryujin Japanese Whisky',
      'Iwai Japanese Whisky', 'Mars Shinshu', 'Fuyu Small Batch Japanese Whisky',
      'Kurayoshi Pure Malt Japanese Whisky', 'Hatozaki Japanese Blended Whisky', 'Kanekou Okinawa Whisky',
      'Kyoto Japanese Whisky', 'Meikakuna Japanese Whisky', 'Sadashi Japanese Whisky',
      'Yamato Armor Takeda Edition Japanese Whisky', 'Chichibu Mizunara'
    ],
    status: 'In Cellar Stock',
  },

  // 7. Specialty Flavored Whiskeys, Lifestyle, Fragrance & Sommelier Gear
  {
    id: 'skrewball-fireball-bird-dog',
    name: 'Skrewball Peanut Butter Whiskey / Fireball Cinnamon Whiskey / Bird Dog Flavored Whiskey',
    category: 'Specialty, Casks & Gear',
    brand: 'Flavored & Infused Whiskey Masters',
    origin: 'California, Kentucky, United States',
    abv: '33% - 40% ABV',
    tastingNotes: 'Skrewball delivers creamy roasted peanut butter warmth. Fireball kicks with real cinnamon heat. Bird Dog features blackberry, peach, and bourbon cream.',
    searchQuery: 'Whiskey',
    tags: ['Skrewball Peanut Butter Whiskey', 'Fireball Cinnamon Whiskey', 'Bird Dog Flavored Whiskey', 'Flavored Bourbon'],
    status: 'In Cellar Stock',
  },
  {
    id: 'goose-island-bourbon-county',
    name: 'Goose Island Bourbon County Brand Stout (Aged in Rare Bourbon Barrels)',
    category: 'Specialty, Casks & Gear',
    brand: 'Goose Island',
    origin: 'Chicago, Illinois, United States',
    abv: '14.2% - 15.1% ABV',
    tastingNotes: 'Imperial stout aged in Buffalo Trace, Heaven Hill, and Wild Turkey bourbon barrels. Rich fudge, toasted coconut, bourbon vanilla, and oak char.',
    searchQuery: 'Bourbon',
    tags: ['Goose Island Bourbon County Brand Stout', 'Bourbon Barrel Aged Stout', 'Goose Island BCBS'],
    status: 'In Cellar Stock',
  },
  {
    id: 'dannam-japanese-whiskey-parfum',
    name: 'D\'Annam Japanese Whiskey Eau de Parfum / Spray',
    category: 'Specialty, Casks & Gear',
    brand: 'd\'Annam Fragrances',
    origin: 'Artisanal Perfumery',
    abv: 'Extrait / Parfum',
    tastingNotes: 'An olfactory tribute to Japanese Mizunara whisky. Top notes of single malt barley, cedarwood, aged oak barrels, amber, and incense resin.',
    searchQuery: 'Japanese',
    tags: ['D\'Annam Japanese Whiskey Eau de Parfum', 'D\'Annam Japanese Whiskey Spray', 'Whiskey Cologne', 'Mizunara Fragrance'],
    status: 'In Cellar Stock',
  },
  {
    id: 'madagascar-bourbon-vanilla',
    name: 'Madagascar Bourbon Vanilla Beans / Pure Bourbon Vanilla Paste',
    category: 'Specialty, Casks & Gear',
    brand: 'Bourbon Origin Botanicals',
    origin: 'Sava Region, Madagascar (Île Bourbon Heritage)',
    abv: 'Botanical Extract',
    tastingNotes: 'Plump Grade A gourmet vanilla beans with high vanillin content. Warm creamy floral balsamic aroma essential for cocktail syrups and spirits pairing.',
    searchQuery: 'Bourbon',
    tags: ['Madagascar Bourbon Vanilla Beans', 'Madagascar Bourbon Vanilla Paste', 'Bourbon Vanilla Extract', 'Ile Bourbon Vanilla'],
    status: 'In Cellar Stock',
  },
  {
    id: 'pendleton-whiskey',
    name: 'Pendleton Canadian Whiskey (Rodeo Heritage / Let\'er Buck)',
    category: 'Specialty, Casks & Gear',
    brand: 'Pendleton',
    origin: 'Hood River, Oregon (Glacier Spring Water from Mt. Hood)',
    abv: '40% ABV',
    tastingNotes: 'Cut with pure glacier-fed spring water. Smooth roasted nuts, caramel, vanilla bean, and gentle rye spice.',
    searchQuery: 'Pendleton',
    tags: ['Pendleton Whiskey', 'Pendleton Canadian Whisky', 'Pendleton 1910', 'Mt Hood Spring Water Whiskey'],
    status: 'In Cellar Stock',
  },
  {
    id: 'glencairn-crystal-glassware',
    name: 'Glencairn Whiskey Glass / Crystal Tumbler Sets / Degustation Copitas',
    category: 'Specialty, Casks & Gear',
    brand: 'Glencairn Crystal Scotland',
    origin: 'East Kilbride, Scotland',
    abv: 'Lead-Free European Crystal',
    tastingNotes: 'The Official Whisky Glass endorsed by the Scotch Whisky Association. Tapered mouth focuses ethanol vapors directly onto the olfactory senses.',
    searchQuery: 'Glass',
    tags: ['Glencairn Whiskey Glass', 'Glencairn Crystal Tumbler Sets', 'Whiskey Tasting Glass', 'Glencairn Official Scotch Glass'],
    status: 'Certified Gear',
  },
  {
    id: 'whiskey-advent-calendars-gear',
    name: 'Whiskey Advent Calendars (2025 / 2026), Whiskey Smoker Kits, Whiskey Stones & Barrel Planters / Aging Barrels',
    category: 'Specialty, Casks & Gear',
    brand: 'Whiskey Europe Cellar Gear & Barware',
    origin: 'Rotterdam Bonded Cellar Accessories',
    abv: 'Sommelier Equipment',
    tastingNotes: '24-day premium advent tasting boxes with wax-dipped 30ml drams, natural soapstone whiskey chilling rocks, cocktail oak smokers, and authentic charred oak aging casks.',
    searchQuery: 'Whiskey',
    tags: [
      'Whiskey Advent Calendars 2025', 'Whiskey Advent Calendars 2026', 'Whiskey Smoker Kits',
      'Whiskey Stones', 'Whiskey Barrel Planters', 'Whiskey Aging Barrels'
    ],
    status: 'Certified Gear',
  },
];
